# Generated by Django 5.1.3 on 2024-11-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_exercicio_remove_workoutexercise_exercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='tipo_usuario',
            field=models.CharField(choices=[('aluno', 'Aluno'), ('professor', 'Professor')], default='aluno', max_length=20),
        ),
    ]
